[package]
name = "mtt"
version = "0.1.0"
edition = "2021"
description = "Poker tournament director for live events"
license = "MIT"
authors = ["Mendel Teichman"]
repository = "https://github.com/maynetee/MTT"

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
tauri = { version = "1.5", features = [ "path-all", "window-all", "fs-all", "dialog-all"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rusqlite = { version = "0.30", features = ["bundled"] }
rand = "0.8"

[features]
custom-protocol = ["tauri/custom-protocol"]
