// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Seq } from "./Seq";
import type { TableNo } from "./TableNo";

/**
 * An undoable or redoable action, for "Undo: bust Alice" style labels.
 */
export type ActionLabel = { seq: Seq, atMs: number, 
/**
 * Event type, e.g. `players_busted`.
 */
kind: string, 
/**
 * Names of the players involved.
 */
names: Array<string>, 
/**
 * Table involved, for table operations and moves.
 */
table: TableNo | null, };
