// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Seq } from "./Seq";

/**
 * An undoable or redoable action, for "Undo: bust Alice" style labels.
 */
export type ActionLabel = { seq: Seq, at_ms: number, 
/**
 * Event type, e.g. `players_busted`.
 */
kind: string, 
/**
 * Names of the players involved.
 */
names: Array<string>, };
