// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Chips } from "./Chips";

/**
 * Ante format of a play level.
 */
export type Ante = { "type": "none" } | { "type": "classic", amount: Chips, } | { "type": "big_blind", amount: Chips, };
