// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Start of an upcoming level.
 */
export type Boundary = { level_index: number, 
/**
 * Clock time until this level starts.
 */
starts_in_ms: number, 
/**
 * Wall-clock start while running.
 */
starts_at_ms: number | null, };
