// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Start of an upcoming level.
 */
export type Boundary = { levelIndex: number, 
/**
 * Clock time until this level starts.
 */
startsInMs: number, 
/**
 * Wall-clock start while running.
 */
startsAtMs: number | null, };
