// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One elimination event (one hand). Groups are numbered in log order.
 */
export type BustGroup = number;
