// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Chips } from "./Chips";
import type { PlayerId } from "./PlayerId";

/**
 * One elimination inside a `BustPlayers` command.
 */
export type BustInput = { player: PlayerId, 
/**
 * Stack at the start of the hand; required for every player of a multi-bust
 * unless all are omitted (full tie).
 */
start_stack?: Chips, };
