// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Chips } from "./Chips";
import type { PlayerId } from "./PlayerId";
import type { SeatRef } from "./SeatRef";

/**
 * One elimination as recorded.
 */
export type Bust = { player: PlayerId, start_stack: Chips | null, seat: SeatRef, };
