// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Chips } from "./Chips";

/**
 * Chip statistics.
 */
export type ChipsView = { starting_stack: Chips, in_play: Chips, avg_stack: Chips | null, 
/**
 * Average stack in big blinds, times 100 (break: next level's big blind).
 */
avg_stack_bb_x100: number | null, };
