// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Chips } from "./Chips";

/**
 * Chip statistics.
 */
export type ChipsView = { startingStack: Chips, inPlay: Chips, avgStack: Chips | null, 
/**
 * Average stack in big blinds, times 100 (break: next level's big blind).
 */
avgStackBbX100: number | null, };
