// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ante } from "./Ante";
import type { Boundary } from "./Boundary";
import type { Chips } from "./Chips";
import type { LevelRow } from "./LevelRow";

/**
 * Clock at the time of the view. While running, the UI counts down to `ends_at_ms` on
 * its own and asks for a fresh view at `recompute_at_ms`; nothing is written per tick.
 */
export type ClockView = { level_index: number, play_level: number | null, is_break: boolean, running: boolean, sb: Chips | null, bb: Chips | null, ante: Ante, duration_ms: number, remaining_ms: number, 
/**
 * Wall-clock end of the current level while running.
 */
ends_at_ms: number | null, 
/**
 * Time spent past the end of the last level.
 */
overtime_ms: number, next: LevelRow | null, 
/**
 * Clock time until the next break starts.
 */
next_break_in_ms: number | null, 
/**
 * Upcoming level starts.
 */
schedule: Array<Boundary>, 
/**
 * Clock time until the last level ends.
 */
structure_ends_in_ms: number, 
/**
 * When this view goes stale while running (level change or registration close).
 */
recompute_at_ms: number | null, };
