// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Clock state as stored in events.
 */
export type Clock = { "type": "paused", level: number, remaining_ms: number, } | { "type": "running", level: number, ends_at_ms: number, };
