// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ante } from "./Ante";
import type { Chips } from "./Chips";

/**
 * Clock at the time of the view.
 */
export type ClockView = { level_index: number, play_level: number | null, is_break: boolean, running: boolean, sb: Chips | null, bb: Chips | null, ante: Ante, duration_ms: number, remaining_ms: number, 
/**
 * Wall-clock end of the current level while running.
 */
ends_at_ms: number | null, };
