// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why the clock changed.
 */
export type ClockReason = "start" | "pause" | "next_level" | "prev_level" | "jump_to" | "next_break" | "adjust" | "set_remaining";
