// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BustInput } from "./BustInput";
import type { Config } from "./Config";
import type { Level } from "./Level";
import type { MoveReason } from "./MoveReason";
import type { PlayerId } from "./PlayerId";
import type { SeatRef } from "./SeatRef";

/**
 * Everything the director can do.
 */
export type Command = { "type": "update_config", config: Config, } | { "type": "update_structure", levels: Array<Level>, } | { "type": "register", name: string, seat?: SeatRef, } | { "type": "unregister", player: PlayerId, } | { "type": "bust_players", busts: Array<BustInput>, } | { "type": "revive_player", player: PlayerId, seat: SeatRef, } | { "type": "move_player", player: PlayerId, to: SeatRef, reason?: MoveReason, } | { "type": "close_registration", } | { "type": "reopen_registration", } | { "type": "finish_tournament", } | { "type": "start_clock", } | { "type": "pause_clock", } | { "type": "undo", } | { "type": "redo", };
