// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Chips } from "./Chips";
import type { Deadline } from "./Deadline";
import type { PayoutConfig } from "./PayoutConfig";
import type { TableNo } from "./TableNo";

/**
 * Tournament settings editable by the director.
 */
export type Config = { name: string, seats_per_table: number, max_tables: number, 
/**
 * Players at the final table; defaults to `seats_per_table`.
 */
final_table_size: number | null, 
/**
 * Rebalance when the largest and smallest tables differ by at least this much.
 */
balance_trigger: number, 
/**
 * Tables to break first, in order; other tables follow from the highest number down.
 */
break_order: Array<TableNo>, starting_stack: Chips, places_paid: number, late_reg: Deadline, payout: PayoutConfig, };
