// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Chips } from "./Chips";
import type { Deadline } from "./Deadline";
import type { MoneyConfig } from "./MoneyConfig";
import type { PayoutConfig } from "./PayoutConfig";
import type { Purchase } from "./Purchase";
import type { TableNo } from "./TableNo";

/**
 * Tournament settings editable by the director.
 */
export type Config = { name: string, seatsPerTable: number, maxTables: number, 
/**
 * Players at the final table; defaults to `seats_per_table`.
 */
finalTableSize: number | null, 
/**
 * Rebalance when the largest and smallest tables differ by at least this much.
 */
balanceTrigger: number, 
/**
 * Tables to break first, in order; other tables follow from the highest number down.
 */
breakOrder: Array<TableNo>, startingStack: Chips, placesPaid: number, lateReg: Deadline, payout: PayoutConfig, 
/**
 * Buy-ins and prize pool; absent for a tournament without money tracking.
 */
money?: MoneyConfig, 
/**
 * Busted players may come back as new entries.
 */
reentry?: Purchase, rebuy?: Purchase, addon?: Purchase, };
