// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Player counts.
 */
export type Counts = { 
/**
 * Distinct players.
 */
unique: number, 
/**
 * First entries plus re-entries.
 */
entries: number, alive: number, busted: number, 
/**
 * Re-entries; present when offered or bought.
 */
reentries?: number, 
/**
 * Rebuys; present when offered or bought.
 */
rebuys?: number, 
/**
 * Add-ons; present when offered or bought.
 */
addons?: number, };
