// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Player counts.
 */
export type Counts = { 
/**
 * Distinct players.
 */
unique: number, entries: number, alive: number, busted: number, };
