// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An ISO 4217 currency: amounts are integers of `10^-exponent` units (EUR: 2, JPY: 0).
 */
export type Currency = { 
/**
 * Three uppercase letters, e.g. `EUR`.
 */
code: string, 
/**
 * Number of minor-unit digits.
 */
exponent: number, };
