// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * When late registration closes (registration is always open during setup).
 */
export type Deadline = { "type": "end_of_play_level", n: number, throughBreak: boolean, } | { "type": "elapsed", ms: number, } | { "type": "manual" };
