// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Money } from "./Money";

/**
 * Deal proposals, one amount per player in the order of the request.
 */
export type DealQuote = { icm: Array<Money>, chipChop: Array<Money>, 
/**
 * Left to play for; `icm` and `chip_chop` add up to the prizes minus this.
 */
playFor: Money, };
