// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Chips } from "./Chips";
import type { Money } from "./Money";

/**
 * A deal to evaluate: the stacks of the remaining players and the prizes they play for.
 */
export type DealRequest = { stacks: Array<Chips>, 
/**
 * Prize of each remaining place, first place first.
 */
prizes: Array<Money>, 
/**
 * Kept aside from the first prize for the players to play for.
 */
playFor?: Money, };
