// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Money } from "./Money";
import type { PlayerId } from "./PlayerId";

/**
 * What one player takes in a deal.
 */
export type DealShare = { player: PlayerId, amount: Money, };
