// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DealShare } from "./DealShare";
import type { Money } from "./Money";

/**
 * A recorded deal.
 */
export type Deal = { 
/**
 * One share per player still in when the deal was made.
 */
amounts: Array<DealShare>, 
/**
 * Left for the winner, on top of their share.
 */
playFor: Money, };
