// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Event } from "./Event";
import type { Seq } from "./Seq";

/**
 * A logged event with its position and wall-clock time.
 */
export type Envelope = { seq: Seq, v: number, at_ms: number, event: Event, };
