// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Bust } from "./Bust";
import type { BustGroup } from "./BustGroup";
import type { Chips } from "./Chips";
import type { Clock } from "./Clock";
import type { ClockReason } from "./ClockReason";
import type { Config } from "./Config";
import type { Finish } from "./Finish";
import type { Level } from "./Level";
import type { MoveReason } from "./MoveReason";
import type { PlayerId } from "./PlayerId";
import type { SeatRef } from "./SeatRef";
import type { TableNo } from "./TableNo";
import type { TournamentId } from "./TournamentId";

/**
 * Domain events.
 */
export type Event = { "type": "tournament_created", id: TournamentId, config: Config, structure: Array<Level>, } | { "type": "config_updated", config: Config, } | { "type": "structure_updated", levels: Array<Level>, clock: Clock, } | { "type": "player_registered", player: PlayerId, name: string, seat: SeatRef, stack: Chips, 
/**
 * Table opened to seat this player, if any.
 */
opened_table: TableNo | null, } | { "type": "player_unregistered", player: PlayerId, } | { "type": "players_busted", group: BustGroup, busts: Array<Bust>, finish: Finish | null, } | { "type": "player_revived", player: PlayerId, seat: SeatRef, } | { "type": "player_moved", player: PlayerId, from: SeatRef, to: SeatRef, reason: MoveReason, } | { "type": "registration_overridden", open: boolean, finish: Finish | null, } | { "type": "tournament_finished", finish: Finish, } | { "type": "clock_changed", reason: ClockReason, clock: Clock, 
/**
 * True for the first start, which moves the tournament out of setup.
 */
starts_tournament: boolean, };
