// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Clock } from "./Clock";
import type { PlayerId } from "./PlayerId";

/**
 * End of the tournament, recorded with the event that caused it.
 */
export type Finish = { winner: PlayerId, 
/**
 * The clock, paused at the moment of the finish.
 */
clock: Clock, };
