// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionLabel } from "./ActionLabel";
import type { Seq } from "./Seq";

/**
 * Undo/redo cursor.
 */
export type History = { 
/**
 * Number of active events.
 */
head: Seq, undo: ActionLabel | null, redo: ActionLabel | null, };
