// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Money } from "./Money";

/**
 * In-the-money status.
 */
export type Itm = { "status": "not_yet", toMoney: number, } | { "status": "bubble" } | { "status": "in_money", 
/**
 * Prize of the next player out, when money is tracked.
 */
nextPayout?: Money, };
