// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * In-the-money status.
 */
export type Itm = { "status": "not_yet", toMoney: number, } | { "status": "bubble" } | { "status": "in_money" };
