// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Level } from "./Level";

/**
 * A level with its display number.
 */
export type LevelRow = { index: number, 
/**
 * 1-based play-level number; `None` for breaks.
 */
playLevel: number | null, level: Level, };
