// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ante } from "./Ante";
import type { Chips } from "./Chips";

/**
 * One level of the structure.
 */
export type Level = { "type": "play", sb: Chips, bb: Chips, ante: Ante, duration_ms: number, } | { "type": "break", duration_ms: number, 
/**
 * Smallest chip kept after a color-up during this break, if any.
 */
color_up: Chips | null, };
