// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a stored log cannot be loaded.
 */
export type LogError = { "code": "MALFORMED", "params": { message: string, } } | { "code": "UNSUPPORTED_FORMAT", "params": { format: number, max: number, } } | { "code": "UNSUPPORTED_VERSION", "params": { v: number, max: number, } } | { "code": "EMPTY_LOG" } | { "code": "MISSING_CREATION" } | { "code": "UNEXPECTED_SEQ", "params": { expected: number, found: number, } } | { "code": "INVALID_HEAD", "params": { head: number, len: number, } } | { "code": "INCONSISTENT", "params": { seq: number, reason: string, } };
