// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A money amount in minor currency units (reserved for the prize pool).
 */
export type Money = number;
