// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Currency } from "./Currency";
import type { Money } from "./Money";
import type { Price } from "./Price";

/**
 * Buy-ins, fees and prize pool settings. All amounts are in minor units.
 */
export type MoneyConfig = { currency: Currency, 
/**
 * Price of a registration (first entry).
 */
buyIn: Price, 
/**
 * Minimum prize pool promised by the house; it pays the overlay.
 */
guarantee?: Money, 
/**
 * Payouts are multiples of this amount (the remainder goes to first place).
 */
roundingUnit: Money, 
/**
 * Smallest payout: places paid shrink until the last one reaches it.
 */
minCash?: Money, };
