// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Currency } from "./Currency";
import type { Money } from "./Money";

/**
 * Prize pool, present when money is tracked. Amounts are in minor units of `currency`.
 */
export type MoneyView = { currency: Currency, 
/**
 * Sum of the prize parts paid by every entry and purchase.
 */
pool: Money, 
/**
 * Fees collected (kept by the house, not in the pool).
 */
fees: Money, guarantee: Money | null, 
/**
 * Paid by the house when the pool is below the guarantee.
 */
overlay: Money, 
/**
 * Distributed to the players: the larger of `pool` and `guarantee`.
 */
effectivePool: Money, 
/**
 * Payouts in force, first place first (`payouts[0]` is 1st place).
 */
payouts: Array<Money>, 
/**
 * The payouts are frozen by `LockPayouts`.
 */
locked: boolean, };
