// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Config } from "./Config";
import type { Level } from "./Level";
import type { TournamentId } from "./TournamentId";

/**
 * Parameters of a new tournament.
 */
export type NewTournament = { id: TournamentId, config: Config, structure: Array<Level>, };
