// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Envelope } from "./Envelope";
import type { Seq } from "./Seq";

/**
 * What a successful dispatch changed, for the host to persist.
 */
export type Outcome = { "type": "recorded", envelope: Envelope, discarded: number, } | { "type": "undone", seq: Seq, } | { "type": "redone", seq: Seq, };
