// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PayoutAmounts } from "./PayoutAmounts";
import type { PlacesPaid } from "./PlacesPaid";

/**
 * Payout settings. Everything is optional: by default `Config.places_paid` places are
 * paid on the default curve.
 */
export type PayoutConfig = { 
/**
 * Rule for the places paid; absent: `Config.places_paid`.
 */
placesPaid?: PlacesPaid, 
/**
 * Split of the pool; absent: the default curve.
 */
amounts?: PayoutAmounts, };
