// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Money } from "./Money";

/**
 * How the effective prize pool is split between the places paid.
 */
export type PayoutAmounts = { "type": "curve", firstShareBps?: number, } | { "type": "custom_bps", bps: Array<number>, } | { "type": "custom_amounts", amounts: Array<Money>, };
