// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payout settings. Reserved: places paid is a fixed number for now.
 */
export type PayoutConfig = Record<string, never>;
