// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Tournament lifecycle as shown to the UI.
 */
export type PhaseName = "setup" | "running" | "finished";
