// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How many places are paid (always at least 1 and at most the number of players).
 */
export type PlacesPaid = { "type": "percent", bps: number, } | { "type": "fixed", n: number, };
