// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Player identifier, allocated sequentially from 1 and never reused.
 */
export type PlayerId = number;
