// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Money } from "./Money";

/**
 * What an entry or a purchase costs, split between the prize pool and the house.
 */
export type Price = { 
/**
 * Part added to the prize pool.
 */
prize: Money, 
/**
 * Part kept by the house (not in the prize pool).
 */
fee: Money, };
