// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Deadline } from "./Deadline";

/**
 * When a purchase can be made (only while the tournament runs). Without a window, it
 * follows registration, the director's override included.
 */
export type PurchaseWindow = { "type": "until", deadline: Deadline, } | { "type": "break_after", n: number, };
