// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Chips } from "./Chips";
import type { Money } from "./Money";
import type { PurchaseWindow } from "./PurchaseWindow";

/**
 * Re-entry, rebuy or add-on settings. Events record the price and stack applied, so
 * editing these never changes past purchases.
 */
export type Purchase = { 
/**
 * Part added to the prize pool (0 without money tracking).
 */
prize: Money, 
/**
 * Part kept by the house (0 without money tracking).
 */
fee: Money, 
/**
 * Chips received.
 */
stack: Chips, 
/**
 * Most purchases of this kind per player (re-entries: not counting the first
 * entry); unlimited when absent.
 */
max?: number, 
/**
 * When it can be bought; absent: while registration is open.
 */
window?: PurchaseWindow, };
