// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlayerId } from "./PlayerId";
import type { SeatRef } from "./SeatRef";

/**
 * One line of the ranking. Alive players come first, without a place.
 */
export type RankingRow = { player: PlayerId, name: string, alive: boolean, seat: SeatRef | null, place: number | null, 
/**
 * Last place of a tie (`place..=place_to`).
 */
place_to: number | null, 
/**
 * The place may still change (late registration open).
 */
provisional: boolean, in_money: boolean, entries: number, };
