// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlayerId } from "./PlayerId";
import type { SeatRef } from "./SeatRef";

/**
 * One line of the ranking. Alive players come first, without a place.
 */
export type RankingRow = { player: PlayerId, name: string, alive: boolean, seat: SeatRef | null, place: number | null, 
/**
 * Last place of a tie (`place..=place_to`).
 */
placeTo: number | null, 
/**
 * The place may still change (late registration open, or the player may re-enter).
 */
provisional: boolean, inMoney: boolean, entries: number, 
/**
 * Rebuys bought; present when any.
 */
rebuys?: number, 
/**
 * Add-ons bought; present when any.
 */
addons?: number, };
