// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Deadline } from "./Deadline";

/**
 * Registration status.
 */
export type RegistrationView = { open: boolean, 
/**
 * Director override (`CloseRegistration` / `ReopenRegistration`), if any.
 */
overrideOpen: boolean | null, deadline: Deadline, 
/**
 * Clock time until the deadline closes registration.
 */
closesInMs: number | null, 
/**
 * Wall-clock close while the clock runs.
 */
closesAtMs: number | null, 
/**
 * Whether a busted player can re-enter now; absent when re-entries are not offered.
 */
reentryOpen?: boolean, 
/**
 * Whether rebuys are open; absent when not offered.
 */
rebuyOpen?: boolean, 
/**
 * Whether add-ons are open; absent when not offered.
 */
addonOpen?: boolean, };
