// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Deadline } from "./Deadline";

/**
 * Registration status.
 */
export type RegistrationView = { open: boolean, 
/**
 * Director override (`CloseRegistration` / `ReopenRegistration`), if any.
 */
override_open: boolean | null, deadline: Deadline, };
