// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Envelope } from "./Envelope";

/**
 * Serializable log: all events plus the undo cursor.
 */
export type SavedLog = { format: number, 
/**
 * Number of active events; the rest are undone and can be redone.
 */
head: number, events: Array<Envelope>, };
