// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SeatNo } from "./SeatNo";
import type { TableNo } from "./TableNo";

/**
 * A seat at a given table.
 */
export type SeatRef = { table: TableNo, seat: SeatNo, };
