// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlayerId } from "./PlayerId";
import type { SeatNo } from "./SeatNo";

/**
 * One seat of a table.
 */
export type SeatView = { seat: SeatNo, player: PlayerId | null, name: string | null, };
