// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlayerId } from "./PlayerId";
import type { SeatRef } from "./SeatRef";

/**
 * A player's seat change inside a table break or final table draw.
 */
export type SeatMove = { player: PlayerId, from: SeatRef, to: SeatRef, };
