// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Seat number within a table, 1-based and clockwise.
 */
export type SeatNo = number;
