// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BalanceStep } from "./BalanceStep";
import type { TableNo } from "./TableNo";

/**
 * What the director should do next, highest priority first; at most one kind is set.
 */
export type Suggestions = { 
/**
 * Redraw everyone at this table for the final table.
 */
final_table: TableNo | null, 
/**
 * Break this table: the others can seat everybody.
 */
break_table: TableNo | null, 
/**
 * Balancing moves, in order.
 */
balance: Array<BalanceStep>, };
