// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SeatNo } from "./SeatNo";
import type { SeatView } from "./SeatView";
import type { TableNo } from "./TableNo";
import type { TableStatus } from "./TableStatus";

/**
 * One table.
 */
export type TableView = { table: TableNo, status: TableStatus, players: number, button: SeatNo | null, 
/**
 * Blinds of the next hand, when the button is known.
 */
nextSb: SeatNo | null, nextBb: SeatNo | null, seats: Array<SeatView>, };
