// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Tournament identifier chosen by the host (ULID or UUID string).
 */
export type TournamentId = string;
