// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChipsView } from "./ChipsView";
import type { ClockView } from "./ClockView";
import type { Config } from "./Config";
import type { Counts } from "./Counts";
import type { History } from "./History";
import type { Itm } from "./Itm";
import type { LevelRow } from "./LevelRow";
import type { PhaseName } from "./PhaseName";
import type { PlayerId } from "./PlayerId";
import type { RankingRow } from "./RankingRow";
import type { RegistrationView } from "./RegistrationView";
import type { TableView } from "./TableView";
import type { TournamentId } from "./TournamentId";
import type { Warning } from "./Warning";

/**
 * Everything the UI renders.
 */
export type View = { generated_at_ms: number, id: TournamentId, phase: PhaseName, winner: PlayerId | null, history: History, config: Config, levels: Array<LevelRow>, clock: ClockView, registration: RegistrationView, counts: Counts, chips: ChipsView, 
/**
 * Places paid, capped by the number of players.
 */
places_paid: number, itm: Itm, ranking: Array<RankingRow>, tables: Array<TableView>, warnings: Array<Warning>, };
