// Host-level types shared by the desktop (Tauri) and browser (WASM) hosts. The core's own
// types are generated by ts-rs into src/bindings/ and re-exported here.
import type { Ante } from "../bindings/Ante";
import type { BalanceStep } from "../bindings/BalanceStep";
import type { BustInput } from "../bindings/BustInput";
import type { ClockView } from "../bindings/ClockView";
import type { Command } from "../bindings/Command";
import type { Config } from "../bindings/Config";
import type { Deadline } from "../bindings/Deadline";
import type { DomainError } from "../bindings/DomainError";
import type { History } from "../bindings/History";
import type { Itm } from "../bindings/Itm";
import type { Level } from "../bindings/Level";
import type { LevelRow } from "../bindings/LevelRow";
import type { NewTournament } from "../bindings/NewTournament";
import type { Outcome } from "../bindings/Outcome";
import type { PhaseName } from "../bindings/PhaseName";
import type { RankingRow } from "../bindings/RankingRow";
import type { SavedLog } from "../bindings/SavedLog";
import type { SeatRef } from "../bindings/SeatRef";
import type { TableView } from "../bindings/TableView";
import type { View } from "../bindings/View";
import type { Warning } from "../bindings/Warning";

export type {
  Ante,
  BalanceStep,
  BustInput,
  ClockView,
  Command,
  Config,
  Deadline,
  DomainError,
  History,
  Itm,
  Level,
  LevelRow,
  NewTournament,
  Outcome,
  PhaseName,
  RankingRow,
  SavedLog,
  SeatRef,
  TableView,
  View,
  Warning
};

/** One line of the tournament list. Mirrored by a serde struct in src-tauri. */
export interface TournamentSummary {
  id: string;
  name: string;
  /** Same values as `View.phase`. */
  phase: PhaseName;
  createdAtMs: number;
  updatedAtMs: number;
  /** `View.counts.unique`. */
  players: number;
  /** `View.counts.alive`. */
  alive: number;
}

/** A new tournament; the host assigns the id. */
export type NewTournamentInput = Omit<NewTournament, "id">;

export type HostError = { code: "HOST_ERROR"; params: { message: string } };
export type NotFoundError = { code: "NOT_FOUND"; params: { id: string } };

/** Every rejection an engine reports: the core's errors plus the host's own. */
export type EngineError = DomainError | HostError | NotFoundError;

export type EngineErrorCode = EngineError["code"];

export function hostError(message: string): HostError {
  return { code: "HOST_ERROR", params: { message } };
}

export function notFound(id: string): NotFoundError {
  return { code: "NOT_FOUND", params: { id } };
}

export function isEngineError(value: unknown): value is EngineError {
  return (
    typeof value === "object" &&
    value !== null &&
    typeof (value as { code?: unknown }).code === "string" &&
    /^[A-Z][A-Z0-9_]*$/.test((value as { code: string }).code)
  );
}

/** Normalizes anything thrown by a host call into an `EngineError`. */
export function toEngineError(value: unknown): EngineError {
  if (isEngineError(value)) return value;
  if (typeof value === "string") {
    try {
      const parsed: unknown = JSON.parse(value);
      if (isEngineError(parsed)) return parsed;
    } catch {
      // Not JSON: a plain message.
    }
    return hostError(value);
  }
  if (value instanceof Error) return hostError(value.message);
  return hostError(String(value));
}

/** Where to save an export; the browser downloads it, the desktop asks with a dialog. */
export interface ExportFile {
  fileName: string;
  bytes: Uint8Array;
  mimeType: string;
}

/**
 * The one interface the UI talks to. Every method rejects with an `EngineError`.
 * `TauriEngine` calls the desktop commands; `WasmEngine` runs mtt-core in the page.
 */
export interface Engine {
  /** "tauri" on the desktop, "wasm" for the browser demo. */
  readonly kind: "tauri" | "wasm";
  listTournaments(): Promise<TournamentSummary[]>;
  createTournament(input: NewTournamentInput): Promise<string>;
  deleteTournament(id: string): Promise<void>;
  /** The view at the host's current time. */
  getView(id: string): Promise<View>;
  /** Runs a command (undo/redo included) and returns the view after it. */
  dispatch(id: string, command: Command): Promise<View>;
  /** Called with the tournament id after every change, from any window or tab. */
  subscribe(listener: (id: string) => void): () => void;
  openDisplayWindow(id: string): Promise<void>;
  /** Closes the window this page runs in (the display). */
  closeCurrentWindow(): Promise<void>;
  /** Resolves to false when the user cancels the save dialog. */
  saveExport(file: ExportFile): Promise<boolean>;
  legacyImportStatus(): Promise<{ available: boolean }>;
  importLegacy(): Promise<string>;
}
